# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rud Running
subtitle: Hej med dig
name: Martin Rud Ehmsen
email: martin@ehmsen.org
description: >- # this means to ignore newlines until "baseurl:"
  En blog om at nå mine løbemål og hvorfor jeg løber.
  Strava: https://www.strava.com/athletes/27789004
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rudning.dk" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ehmsen
timezone: "Europe/Copenhagen"
site.locale: "da-DK"
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
# teaser: /assets/images/500x300.png
logo: "/assets/images/Rud Running Logo.svg"
# masthead_title: "My Custom Title"
breadcrumbs: false  # disabled by default
date_format: "%Y-%m-%d"
words_per_minute: 250
permalink: pretty

include:
  - "_pages"
  - "_posts"

social:
  type: Person  # Person or Organization (defaults to Person)
  name: Martin Rud Ehmsen # If the user or organization name differs from the site's name
  links:
    - "https://www.strava.com/athletes/27789004"
    - "https://www.linkedin.com/in/martinrehmsen/"

author:
  name: "Martin Rud Ehmsen"
  avatar: "/assets/images/mre_square.jpg"
  bio: "Jeg **løber**." # Note: Markdown is allowed
  location: "Odense, Danmark"
  links:
    - label: "Strava"
      icon: "fab fa-fw fa-strava"
      url: "https://www.strava.com/athletes/27789004"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/martinrehmsen/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ehmsen"

footer:
  links:
    - label: "Strava"
      icon: "fab fa-fw fa-strava"
      url: "https://www.strava.com/athletes/27789004"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/martinrehmsen/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ehmsen"

collections:
  runs:
    output: true
    distance: marathon
  routes:
    output: true
    distance: marathon

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true    
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Build settings
# theme: minima
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
